project:
  type: website
  output-dir: docs

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true
    toc-location: right
    toc-depth: 3


website:
  title: "CartoExpert"
  navbar:
    background: "#E30F1B"
    foreground: "white"
    left:
      - text: "Général"
        menu:
        - text: "Contexte du projet"
          href: index.qmd
        - text: "Prérequis de travail"
          href: installations.qmd
      - text: "Exploitation"
        menu:
        - text: "Utiliser CartoExpert au quotidien"
          href: pres_syst.qmd
        - text: "Centraliser les données"
          href: standardiser_data2csv.qmd
        - text: "Interconnecter les données via Oméka S"
          href: bdd_omeka.qmd
      - text: "Boite à outils"
        menu:
        - text: "Hypothes.is comme outil collaboratif"
          href: hypothesis.qmd
        - text: "ListMonk pour gérer les campagnes de mailing"
          href: listmonk.qmd
        - text: "ScanR comme source de données"
          href: scanr_extract.qmd
        - text: "Exploiter le web sémantique pour les métadonnées"
          href: dico_rdf.qmd
        - text: "Utilisation de l'IA Générative"
          href: iag.qmd

  page-footer:
    left: "Direction de la Recherche de Paris 8"
    center: |
      <div class="footer-img">
        <img src="assets/img/logo_paris8_couleurs-officielles.png" alt="Logo de l'Université" class="footer-logo">
      </div>  
    right: "Documentation interne, ne pas diffuser"