project:
  type: website
  output-dir: docs

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true
    toc-location: right
    toc-depth: 3

website:
  title: "CartoExpert"
  navbar:
    background: "#E30F1B"
    foreground: "white"
    left:
      - text: "Général"
        menu:
          - text: "Contexte du projet"
            href: index.qmd
          - text: "Prérequis de travail"
            href: installations.qmd

      - text: "Données"
        menu:
          - text: "Préparer les données (CSV)"
            href: donnees/standardiser_data2csv.qmd
          - text: "Importer dans Oméka S"
            href: donnees/bdd_omeka.qmd
          - text: "Extraire depuis ScanR"
            href: donnees/scanr_extract.qmd

      - text: "Outils"
        menu:
          - text: "CartoExpert — présentation"
            href: outils/pres_syst.qmd
          - text: "---"
          - text: "ValiDatas"
            href: outils/introduction_validata.qmd
          - text: "↳ Guide opérateur"
            href: outils/guide_operateur_validata.qmd
          - text: "↳ Documentation technique"
            href: outils/doc_tech_validata.qmd

      - text: "Ressources"
        menu:
          - text: "Hypothes.is comme outil collaboratif"
            href: ressources/hypothesis.qmd
          - text: "ListMonk pour les campagnes de mailing"
            href: ressources/listmonk.qmd
          - text: "Web sémantique & RDF"
            href: ressources/dico_rdf.qmd
          - text: "Utilisation de l'IA Générative"
            href: ressources/iag.qmd

  page-footer:
    left: "Direction de la Recherche de Paris 8"
    center: |
      <div class="footer-img">
        <img src="https://sedozed.github.io/valo-p8/assets/img/logo_paris8_couleurs-officielles.png" alt="Logo de l'Université" class="footer-logo">
      </div>
    right: "Documentation interne, ne pas diffuser"