---
title: 'Script de fusion de tableur : "DataMerge"'
format: html
lang: fr
---

DataMerge est un outil artisanale conçu pour simplifier et fiabiliser la fusion de données issues de plusieurs fichiers Excel. Il permet d’associer automatiquement des informations provenant d’un fichier source vers un fichier cible en s’appuyant sur des clés de correspondance choisies par l’utilisateur (souvent un nom de famille). Même s’il reste rudimentaire, DataMerge accélère la collecte d’informations provenant de plusieurs tableurs en supprimant une partie des manipulations manuelles répétitives, longues et susceptibles de générer des erreurs.

La conception de ce script a, avant tout, été motivé par l'idée d'effectuer cette automatisation localement plutôt que d'utiliser des algorithmes non-propriétaire dans un contexte où les données traitées sont souvent sensibles (données personnelles, données confidentielles, etc...). L'ensemble des fichiers permettant le fonctionnement du script sont disponible sur le GitHub du projet. Enfin, il est très programme que DataMerge soit amené à évoluer à l'avenir, auquel cas les informations d'utilisation seront mise à jour sur cette page?=.

## Exemple d'utilisation

Un service X de l’université transmet un fichier tableur contenant diverses informations sur des étudiants ou des personnels (adresses mises à jour, nouveaux statuts, changements administratifs, etc.). De notre côté, nous disposons déjà d’une base de données interne, mais seules certaines des informations envoyées nous concernent réellement. De plus, le fichier transmis peut contenir des noms ou identifiants qui n’existent pas dans notre propre base, et qu’il faut donc ignorer pour éviter des erreurs de mise à jour.

Sans outil dédié, la procédure consiste à parcourir manuellement le fichier reçu, rechercher chaque personne dans notre tableau interne, vérifier si elle existe, puis reporter uniquement les données pertinentes. Cette opération est longue, répétitive et particulièrement sensible aux erreurs humaines. Avec DataMerge, il suffit de sélectionner dans l'ordre :

1. le fichier transmis par l’autre service *(ou une première extraction orientée "machine" de certaines données dudit fichier)*,

2. notre fichier interne *(ou une extraction dudit fichier reprenant la structure des données)*,

3. la colonne servant de clé d’identification *(souvent le nom de famille)*,

4. la colonnes des données à ajouter / mettre à jour dans notre fichier interne.

Le programme se charge alors de faire correspondre automatiquement les entrées présentes dans les deux fichiers (les noms de familles identiques par exemple), d’ignorer celles qui ne figurent pas dans notre base, et de mettre à jour uniquement les informations pertinentes. 