---
title: "Prérequis et installations"
lang: fr
---

Le projet CartoExpert nécessite la mobilisation d'un certain nombre de ressources, qu'elles soient humaines, techniques ou logicielles pour pouvoir opérer efficacement. Cette page de la documentation se focalisera donc sur ces prérequis.

# Prérequis côté hardware
Côté hardware, pour travailler de façon optimale, besoin d'une machine capable de supporter le multitasking lourd (développement, navigation dans des données, hébergement de serveur local, ...). Focus donc sur la RAM, le processeur et le stockage avant tout. _(Note pour plus tard : modifier ces infos en fonction des constats lié à oLlama)_

Avoir deux écrans est quasiment indispensable tant la navigation entre les fenêtres se fait tout le temps

# Prérequis côté software
En terme d'OS, le choix à privilégier est une base **Linux** car Oméka S semble rencontrer des problèmes sur Windows et nécessite trop de ressource pour le débugger. Plus précisément, un **Debian** est recommandé puisque les serveurs de la DSR fonctionnent sur une base Debian.

**Note** : La navigation / l'écriture / ... sur Linux se fait plus facilement via lignes de commandes. Cependant pas de panique, la communauté a très bien documenté le tout, notamment pour ce que nous voulons faire.

## Logiciel d'écriture
Les premiers logiciels à avoir. N'ont pas besoin de droit administrateur pour s'installer et/ou peuvent être installés parfois par défaut.

- **Microsoft 365** (Excel) ou autre tableur pour naviguer/écrire dans les documents CSV.

- **Visual Studio Code** pour écrire avec différents langages (.qmd pour la documentation et .ttl pour le dictionnaire RDF par exemple)

- **GitHub Desktop** (Import du repository localement & transfert des modifications effectué localement sur ledit repository via des MaJ)

### Des plugins pour VSCode
Liste de quelques modules à installer pour une utilisation efficace.

- Quarto (_Quarto)

- Python (_Microsoft_)

- RDF Sketch (_Zazuko_)

# Configurer le serveur local

[introduction sur pk configurer un serveur local, c-a-d de configurer la bdd de façon à pouvoir la téléverser directement sur les serveurs du SVR, eux mêmes tournant sur Debian]

## LAMP = Acronyme pour "Linux, Apache, MySQL/MariaDB, PhP"

### Apache
La première pierre de notre environnement préliminaire d'édition est le logiciel open-source [Apache](https://www.hostinger.com/fr/tutoriels/quest-ce-quapache). Open-source et utilisé par près de la moitié des sites web du net, Apache va nous permettre de créer notre site internet (local) et d'y installer notre outil de gestion des données, tout en profitant de la très vaste documentation disponible pour faire fonctionner le serveur.

1. https://www.it-connect.fr/installer-un-serveur-lamp-linux-apache-mariadb-php-sous-debian-11/#A_Installer_Apache_sous_Debian_13
2. https://www.it-connect.fr/installer-un-serveur-lamp-linux-apache-mariadb-php-sous-debian-11/#B_Lemplacement_de_la_configuration_Apache2

### MariaDB
La seconde pierre angulaire de notre environnement préliminaire d'édition est le dérivé communautaire et open-source de MySQL : [MariaDB](https://fr.wikipedia.org/wiki/MariaDB). [a completer]

1. https://www.it-connect.fr/installer-un-serveur-lamp-linux-apache-mariadb-php-sous-debian-11/#D_Installer_MySQLMariaDB_sous_Debian_13
2. https://phoenixnap.com/kb/how-to-create-mariadb-user-grant-privileges

### PhP (et PhPmyAdmin)
Enfin, la troisième pierre angulaire de notre environnement préliminaire d'édition est le langage de programmation orienté objet : [PHP](https://fr.wikipedia.org/wiki/PHP). Celui-ci permet la création de page web dite dynamiques [...] qui, à titre informatif, a notamment permis la création de Wikipédia ou de Facebook.

- https://www.it-connect.fr/installer-un-serveur-lamp-linux-apache-mariadb-php-sous-debian-11/#C_Installer_PHP_sous_Debian_13
- https://tecadmin.net/how-to-install-php-on-debian-13/ (notamment pour certaines extensions)

- https://www.php.net/manual/en/mbstring.installation.php

**Installer phpMyAdmin**
Pas vraiment une pierre angulaire dans notre cas, [phpMyAdmin](https://www.phpmyadmin.net/) est une application web offrant une interface web de gestion pour MariaDB (entre autres) qu'il est malgré tout recommandé d'installer dans notre serveur local.

- https://www.it-connect.fr/installer-phpmyadmin-sur-debian-11-et-apache/


## Installer Oméka S 

[Télécharger Oméka S](omeka.org/s/download/) et l'extraire ici : "var/www/html" puis, dans le dossier (renommé), aller dans "config" puis "database.ini", définir un user / mdp / databasename puis "host=localhost"

Pour accéder ensuite à l'interface Oméka S : 
- localhost/[nom_dossier]/admin

Pour installer des modules (important) : Les télécharger [ici](https://omeka.org/s/modules/) puis les décompresser dans "var/www/html/[nom_dossier]/modules"