---
title: 'Réunir des données éparpillées en un endroit'
lang: fr
---

[introduction contexte]
# Prendre connaissance des diverses données éparpillées
Blabla + parler des sources connues

# Etablir une structure
Création d'une base centrale qui accueillera l'ensemble des données réunies (tableur, csv, ...). Conseil : se baser sur un jeu de donnée existant complet puis l'aggrémenter au fur et à mesure (nouvelles colonnes, autre données, ...)

Image + descripion

# Homogénéiser les données
redir vers [DataMerge](datamerge_use.qmd) 
Trouver identifiant unique (souvent le nom de l'entité physique ou morale) et y accrocher les données utiles trouvables dans tous les docs de façon uniforme 

## Cas spécial : Effectuer des "approximations"
Certaines façon d'écrire ou d'évoquer une information ne peut pas être aussi simplement uniformisé (par exemple, nomenclature HCERES2022 vers HCERES2024, plus précis) et nécessite quelques approximations et interprétations.
TOUJOURS MENTIONNER QUE CES DONNEES SONT DES ESTIMATIONS + SUJETTE A MODIFICATION OFFICIELLE 

# Fusionner les données entres-elles
Dénominateur commun + info du doc1 + info du doc2 

